services:
  backend:
    build:
      context: ./backend
    restart: always
    command: python main.py
    environment:
      - DATABASE_URL
      - ADMIN_ID
      - BOT_TOKEN
      - TRIBUTE_API_KEY
      - OPENAI_API_KEY
      - TELEGRAM_PROXY
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  bot:
    build:
      context: ./backend
    restart: always
    command: sh start_bot.sh
    environment:
      - DATABASE_URL
      - ADMIN_ID
      - BOT_TOKEN
      - TRIBUTE_API_KEY
      - OPENAI_API_KEY
      - TELEGRAM_PROXY
    depends_on:
      - postgres
      - backend
      - telegram-bot-api

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    restart: always
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
    command: ["--local"]
    volumes:
      - telegram_bot_api_data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: sovenok
      POSTGRES_USER: sovenok
      POSTGRES_PASSWORD: sovenok
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  telegram_bot_api_data:
