services:
  backend:
    build:
      context: ./backend
    container_name: sovenok-backend
    restart: always
    command: python main.py
    environment:
      - DATABASE_URL
      - ADMIN_ID
      - BOT_TOKEN
      - TRIBUTE_API_KEY
      - OPENAI_API_KEY
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  bot:
    build:
      context: ./backend
    container_name: sovenok-bot
    restart: always
    command: sh start_bot.sh
    environment:
      - DATABASE_URL
      - ADMIN_ID
      - BOT_TOKEN
      - TRIBUTE_API_KEY
      - OPENAI_API_KEY
    depends_on:
      - postgres
      - backend

  postgres:
    image: postgres:16-alpine
    container_name: sovenok-postgres
    restart: always
    environment:
      POSTGRES_DB: sovenok
      POSTGRES_USER: sovenok
      POSTGRES_PASSWORD: sovenok
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
